### ISSUE TITLE
Project status/dependencies

### ISSUE THREAD

**Issue by caprilesport** [shanecelis/bevy_minibuffer#1]
Hey mate! Really nice project!

This is exactly something I was looking for a project I'm working with bevy (a 3D editor) that I plan to use something like this to get some vim-like functionality.

I know the project is in it's early stages but I tried to add it as a dependency and I'm having issues with the dependencies (the  error shown below, related to [text_style](https://github.com/shanecelis/bevy_minibuffer/blob/c4db46ec84f062fbf824195b3b5bc3f7e3642aed/Cargo.toml#L16)).

```
error: failed to select a version for the requirement `text-style = "^0.4.0"`
candidate versions found which didn't match: 0.3.0, 0.2.0, 0.1.1, ...
location searched: crates.io index
required by package `bevy_minibuffer v0.1.0-alpha.1 (https://github.com/shanecelis/bevy_minibuffer#c4db46ec)`
    ... which satisfies git dependency `bevy_minibuffer`
```

Just wanted to know what is the status of the project, and if you plan on releasing an 0.1.0 any time soon without this patched dependencies, or if I could be of help with anything for reaching this state.

Cheers and thanks for your work on this!

**Comment by shanecelis** [comment]
Hey! Thanks for the interest.

Yeah, the patched dependencies have kept me from releasing it. I had been using [Asky](https://github.com/axelvc/asky), which is a terminal-centric plugin. But I'd decided to just rewrite Asky for bevy located in [bevy_asky](https://github.com/shanecelis/bevy_asky) directly to avoid the patched dependencies, which would probably be more performant anyway. I got stalled on it because I started to kind of reach for the moon in terms of having a richer-than-just-text UI and the UI focus plugin wasn't working for a couple cases. (Specifically I couldn't get it to change focus between a group of checkboxes or radio buttons; I didn't file an issue though.) My plan was to get bevy_asky working then use that in bevy_minibuffer.

Now, if I were less ambitious, like I was before I saw Asky, I'd accept textual input, and then make every other input a variation of that. Then I'd finally be able to release bevy_minibuffer.

So in answer to your question, development is stalled but not abandoned. My attention isn't currently on fixing it right now. If you wanted to help, you could kick the tires of bevy_asky. I pushed a few commits, so that it's in a working state. It's the `checkbox_group` example that dragged me down. I notice too that I should file a PR to [ui-navigation](https://github.com/shanecelis/ui-navigation/tree/bevy-0.14) to update it to bevy-0.14.

Thanks for dropping me a line. Helps to motivate sometimes.

**Comment by shanecelis** [comment]
Hi @caprilesport, I made some headway on the focus problem that had stymied me. I haven't published bevy_asky yet, but I think you can do a little test drive on bevy_minibuffer now. The examples all work and demonstrate now to principle ways to query the user using async or using triggers.

**Comment by shanecelis** [comment]
Nevermind. Looks like I broke something important trying to get it into a kick-tires state. Bah.

**Comment by caprilesport** [comment]
Hey @shanecelis! 

Nice to see the updates! I did a quick prototype here and it seems to be working fine! Hope to have some time soon to dive deeper.

Thanks a lot for the quick fix and the ping here! :)
